version: '3.1'
services:
  db:
    image: mariadb:10.6.4
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
    volumes:
      - lease-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: ./lease-api
      dockerfile: Dockerfile
    image: lease:latest
    restart: always
    env_file:
      - .env
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      FLYWAY_URL: jdbc:mariadb://db:3306/${MYSQL_DATABASE}
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}

  ui:
    build:
      context: ./lease-ui
      args:
        REACT_APP_API_ADDRESS: http://localhost:9090/api
      dockerfile: Dockerfile
    image: lease-ui:latest
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  lease-db:
