server:
  port: 9090
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    show-sql: true
  data:
    rest:
      base-path: /api
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /docs
    try-it-out-enabled: true
    operations-sorter: method
    filter: true
  api-docs:
    path: /api-docs
