server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
spring:
  profiles:
    active: local
  data:
    rest:
      base-path: /api
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /docs
    try-it-out-enabled: true
    operations-sorter: method
    filter: true
  api-docs:
    path: /api-docs
