spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lease
    username: admin
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver

openapi:
  dev-url: http://localhost:9090/api
